
site:
  about:
    siteName: Clog
    siteDescription: Simple yet powerful logging and string formatting for Java

theme:
  social:
    github: 'JavaEden/Clog'
  primaryColor: '#2a623d'
  menu:
    - type: 'wiki'
      asSubmenu: true
      submenuTitle: 'Wiki'
    - type: 'submenu'
      title: 'Integrations'
      menu:
        - type: 'page'
          itemId: 'Clog4j'
        - type: 'page'
          itemId: 'Android Clog'
    - type: 'javadocPackages'
    - type: 'javadocClasses'
  trianglifyOptions:
    x_colors: ['#000', '#2a623d', '#000']

allPages:
  components:
    - type: pageContent
      order: 10
    - type: prism
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'groovy'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'

services:
  publications:
    stages:
      - type: ghPages
        username: 'cjbrooks12'
        repo: 'JavaEden/Clog'
      - type: githubReleases
        repo: 'JavaEden/Clog'
