
site:
  about:
    siteName: Clog4j
    siteDescription: Clog logger implementation for SLF4j

theme:
  social:
    github: 'JavaEden/Clog'
  primaryColor: '#2a623d'
  menu:
    - type: 'link'
      title: 'Home'
      url: '#{$0|baseUrl}/'
    - type: 'wiki'
      title: 'Wiki'
    - type: 'dropdown'
      title: 'Integrations'
      menu:
        - type: 'link'
          title: 'Clog4j'
          url: '#{$0|baseUrl}/clog4j'
        - type: 'link'
          title: 'Android Clog'
          url: '#{$0|baseUrl}/android-clog'
    - type: 'javadocPackages'
    - type: 'javadocClasses'
  trianglifyOptions:
    x_colors: ['#000', '#2a623d', '#000']

allPages:
  components:
    - type: pageContent
      order: 10
    - type: prism
      githubTheme: 'darcula'
      languages:
        - 'yaml'
        - 'java'
        - 'groovy'
        - 'markdown'
      plugins:
        - 'line-numbers'
        - 'line-highlight'
        - 'toolbar'
        - 'show-language'
        - 'copy-to-clipboard'
